echo "  "
echo "  "
echo "                     | "
echo "               pN▓▓g▓p▓g▓▓g▓▓▓▓ge "
echo "             ▓▓▓▓▓▓▓▓▒▒▓▒▓▒▓▓▓▓ "
echo "           _0▓▓▒▓▒▓▒▒▓▓▓▓▓▓▓▓▓▓! "
echo "           4▓▓▓▓▓▓▒▒▒▓▒▒▓▓▓▓▓▓▓▓Y  "
echo "           |     ┴┴&00▒▒0▓▓▓MMM, M |  "
echo "                     M▒▒▓M?           "
echo "         |          000QQ00        |     "
echo "         #▓▓______g▓0▒▒▒▒P________0    "
echo "         #▓▓0g____p#▒▒04▓▓▒▒&,____M#      "
echo "         0▓▓▓▓▓▓▓▓00    ]0▓▓▓▓▓▓00         "
echo "          |\j▓▓▓▓▓0       0▓▓▓▓▓▓4M     "
echo "           |\#▓▓▓▓▓&&▓▓gg▓▓▓▓00& |             DEDSEC.CTOS    "
echo "              ▓▓▓000▓▓▓00▓▓▓▓▓  d "
echo "           %  ¼▓▓▓  ┴P ▓ ¼▓▓▓▓|¼¼|          _____Ares-dev____"
echo "           1▓g▓▓]   @▓▓9WATCH_DOGS "
echo "            ┴▓0_▓▓▓p▓g▓▓▓▓  "
echo "              @▒▓▓▓▓      ▓▓▓▓▒ "
echo "               M0▒▒   ▒▒▒▒ˆ "
echo "                  \ "
